### ISSUE TITLE
xtrabackup: Error: xtrabackup_init_temp_log() failed.

### ISSUE THREAD

**Issue by zhangzhaorui** [gites/k8s-mysql-group-replication#7]
Hello boss！ I had some problems deploying with your yaml file，first I create pv&pvc  ，second  I create svc ，third，I create the configmap ，in the end I create statefulset。But ，When my first pod myslq-0 was successfully initialized, the second pod mysql-1 encountered problems！
Log as follows：

[root@idc-k8smaster-javaphp-001 k8s-mysql-group-replication]# kubectl logs -f mysql-1 clone-mysql
+ [[ -d /var/lib/mysql/mysql ]]
++ hostname
+ [[ mysql-1 =~ -([0-9]+)$ ]]
+ ordinal=1
+ [[ 1 -eq 0 ]]
+ ncat --recv-only mysql-0.mysql 3307
+ xbstream -x -C /var/lib/mysql
/mnt/config-map/clone-mysql.sh: line 12: ncat: command not found
+ xtrabackup --prepare --target-dir=/var/lib/mysql
xtrabackup version 2.3.4 based on MySQL server 5.6.24 Linux (x86_64) (revision id: e80c779)
xtrabackup: cd to /var/lib/mysql
xtrabackup: Error: cannot open ./xtrabackup_checkpoints
xtrabackup: error: xtrabackup_read_metadata()
xtrabackup: This target seems not to have correct metadata...
2018-09-17 06:56:48 7f4a09b24740  InnoDB: Operating system error number 2 in a file operation.
InnoDB: The error means the system cannot find the path specified.
xtrabackup: Warning: cannot open ./xtrabackup_logfile. will try to find.
2018-09-17 06:56:48 7f4a09b24740  InnoDB: Operating system error number 2 in a file operation.
InnoDB: The error means the system cannot find the path specified.
  xtrabackup: Fatal error: cannot find ./xtrabackup_logfile.
xtrabackup: Error: xtrabackup_init_temp_log() failed.

**Comment by zhangzhaorui** [comment]
kubectl logs -f mysql-0 xtrabackup，I find some error.
+ sleep 1
+ /usr/bin/mysql -h mysql-0.mysql -e 'SELECT 1'
/mnt/config-map/xtrabackup.sh: line 7: /usr/bin/mysql: No such file or directory
+ sleep 1
+ /usr/bin/mysql -h mysql-0.mysql -e 'SELECT 1'
/mnt/config-map/xtrabackup.sh: line 7: /usr/bin/mysql: No such file or directory
+ sleep 1
+ /usr/bin/mysql -h mysql-0.mysql -e 'SELECT 1'
/mnt/config-map/xtrabackup.sh: line 7: /usr/bin/mysql: No such file or directory
+ sleep 1
+ /usr/bin/mysql -h mysql-0.mysql -e 'SELECT 1'
/mnt/config-map/xtrabackup.sh: line 7: /usr/bin/mysql: No such file or directory
+ sleep 1
+ /usr/bin/mysql -h mysql-0.mysql -e 'SELECT 1'
/mnt/config-map/xtrabackup.sh: line 7: /usr/bin/mysql: No such file or directory
+ sleep 1
+ /usr/bin/mysql -h mysql-0.mysql -e 'SELECT 1'
/mnt/config-map/xtrabackup.sh: line 7: /usr/bin/mysql: No such file or directory
+ sleep 1
+ /usr/bin/mysql -h mysql-0.mysql -e 'SELECT 1'
/mnt/config-map/xtrabackup.sh: line 7: /usr/bin/mysql: No such file or directory
+ sleep 1
+ /usr/bin/mysql -h mysql-0.mysql -e 'SELECT 1'
/mnt/config-map/xtrabackup.sh: line 7: /usr/bin/mysql: No such file or directory
+ sleep 1
+ /usr/bin/mysql -h mysql-0.mysql -e 'SELECT 1'
/mnt/config-map/xtrabackup.sh: line 7: /usr/bin/mysql: No such file or directory
+ sleep 1
+ /usr/bin/mysql -h mysql-0.mysql -e 'SELECT 1'
/mnt/config-map/xtrabackup.sh: line 7: /usr/bin/mysql: No such file or directory
+ sleep 1
+ /usr/bin/mysql -h mysql-0.mysql -e 'SELECT 1'
/mnt/config-map/xtrabackup.sh: line 7: /usr/bin/mysql: No such file or directory
+ sleep 1
+ /usr/bin/mysql -h mysql-0.mysql -e 'SELECT 1'
/mnt/config-map/xtrabackup.sh: line 7: /usr/bin/mysql: No such file or directory
+ sleep 1
+ /usr/bin/mysql -h mysql-0.mysql -e 'SELECT 1'
/mnt/config-map/xtrabackup.sh: line 7: /usr/bin/mysql: No such file or directory
+ sleep 1
+ /usr/bin/mysql -h mysql-0.mysql -e 'SELECT 1'
/mnt/config-map/xtrabackup.sh: line 7: /usr/bin/mysql: No such file or directory
+ sleep 1
+ /usr/bin/mysql -h mysql-0.mysql -e 'SELECT 1'
/mnt/config-map/xtrabackup.sh: line 7: /usr/bin/mysql: No such file or directory
+ sleep 1

**Comment by gites** [comment]
This repo is DEPRECATED.
Please use official MySQL operator instead --> https://github.com/oracle/mysql-operator
