### ISSUE TITLE
Serious reliability issue 

### ISSUE THREAD

**Issue by AmreeshTyagi** [gites/k8s-mysql-group-replication#8]
Thanks for providing this solution. Everything works fine initially.

`SELECT * FROM replication_group_members` was showing all group members online.

group_replication_applier | ab5c8ecd-ed92-11e8-9445-2e3b2c86be4a | mysql-0.mysql | 3306 | ONLINE
-- | -- | -- | -- | --
group_replication_applier | caddcd94-ed92-11e8-9a8b-f667d83e57a5 | mysql-1.mysql | 3306 | ONLINE
group_replication_applier | f03a662f-ed92-11e8-9a13-c278ec5cf7bd | mysql-2.mysql | 3306 | ONLINE

But when, I tried to play around it & deleted 2 PODS `mysql-1` & `mysql-2`. It was still showing 

group_replication_applier | ab5c8ecd-ed92-11e8-9445-2e3b2c86be4a | mysql-0.mysql | 3306 | ONLINE
-- | -- | -- | -- | --
group_replication_applier | caddcd94-ed92-11e8-9a8b-f667d83e57a5 | mysql-1.mysql | 3306 | UNREACHABLE
group_replication_applier | f03a662f-ed92-11e8-9a13-c278ec5cf7bd | mysql-2.mysql | 3306 | ONLINE

After that, I am not able to execute write/insert query. Read operations are working fine.

Please let me know, if someone has tried similar thing & faced such issue. Any solution?

**Comment by gites** [comment]
This repo is DEPRECATED
Please use official MySQL operator instead --> https://github.com/oracle/mysql-operator
